# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    node_16_x:
      node_version: 16.6.1

steps:
- task: NodeTool@0 
  inputs:
    versionSpec: $(node_version)

- script: npm install
  displayName: 'All server package installed'

- script: 
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Npm@1
  inputs:
    workingDir: '/client'

- script: npm install
  displayName: 'All client package installed'

- script: npm test
  displayName: 'Run a unit test for Login feature'

